In [1]:
import pandas
import re
import nltk

#nltk.download()  

from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.decomposition import PCA

In [2]:
#Read in data set as a tab-delimited file

data = pandas.read_csv("amazon_alexa.tsv", delimiter = "\t")

In [3]:
#Look at dataset

data

rating       date             variation  \
0          5  31-Jul-18      Charcoal Fabric    
1          5  31-Jul-18      Charcoal Fabric    
2          4  31-Jul-18        Walnut Finish    
3          5  31-Jul-18      Charcoal Fabric    
4          5  31-Jul-18      Charcoal Fabric    
5          5  31-Jul-18  Heather Gray Fabric    
6          3  31-Jul-18     Sandstone Fabric    
7          5  31-Jul-18      Charcoal Fabric    
8          5  30-Jul-18  Heather Gray Fabric    
9          5  30-Jul-18  Heather Gray Fabric    
10         5  30-Jul-18      Charcoal Fabric    
11         5  30-Jul-18      Charcoal Fabric    
12         5  30-Jul-18           Oak Finish    
13         5  30-Jul-18      Charcoal Fabric    
14         5  30-Jul-18           Oak Finish    
15         5  30-Jul-18  Heather Gray Fabric    
16         5  30-Jul-18  Heather Gray Fabric    
17         5  30-Jul-18  Heather Gray Fabric    
18         5  30-Jul-18      Charcoal Fabric    
19         4  30-Jul-18     Sandstone Fabric    
20         5  30-Jul-18      Charcoal Fabric    
21         5  30-Jul-18      Charcoal Fabric    
22         4  30-Jul-18  Heather Gray Fabric    
23         5  30-Jul-18      Charcoal Fabric    
24         3  30-Jul-18     Sandstone Fabric    
25         5  30-Jul-18     Sandstone Fabric    
26         5  30-Jul-18      Charcoal Fabric    
27         5  30-Jul-18      Charcoal Fabric    
28         4  30-Jul-18      Charcoal Fabric    
29         5  30-Jul-18      Charcoal Fabric    
...      ...        ...                   ...   
3120       5  30-Jul-18            Black  Dot   
3121       5  30-Jul-18            Black  Dot   
3122       3  30-Jul-18            Black  Dot   
3123       4  30-Jul-18            Black  Dot   
3124       5  30-Jul-18            Black  Dot   
3125       4  30-Jul-18            Black  Dot   
3126       5  30-Jul-18            Black  Dot   
3127       4  30-Jul-18            Black  Dot   
3128       5  30-Jul-18            White  Dot   
3129       4  30-Jul-18            White  Dot   
3130       5  30-Jul-18            Black  Dot   
3131       5  30-Jul-18            Black  Dot   
3132       5  30-Jul-18            Black  Dot   
3133       4  30-Jul-18            White  Dot   
3134       5  30-Jul-18            Black  Dot   
3135       5  30-Jul-18            White  Dot   
3136       4  30-Jul-18            Black  Dot   
3137       5  30-Jul-18            Black  Dot   
3138       5  30-Jul-18            White  Dot   
3139       5  30-Jul-18            White  Dot   
3140       4  30-Jul-18            White  Dot   
3141       3  30-Jul-18            Black  Dot   
3142       4  30-Jul-18            White  Dot   
3143       5  30-Jul-18            Black  Dot   
3144       5  30-Jul-18            Black  Dot   
3145       5  30-Jul-18            Black  Dot   
3146       5  30-Jul-18            Black  Dot   
3147       5  30-Jul-18            Black  Dot   
3148       5  30-Jul-18            White  Dot   
3149       4  29-Jul-18            Black  Dot   

                                       verified_reviews  feedback  
0                                         Love my Echo!         1  
1                                             Loved it!         1  
2     Sometimes while playing a game, you can answer...         1  
3     I have had a lot of fun with this thing. My 4 ...         1  
4                                                 Music         1  
5     I received the echo as a gift. I needed anothe...         1  
6     Without having a cellphone, I cannot use many ...         1  
7     I think this is the 5th one I've purchased. I'...         1  
8                                           looks great         1  
9     Love it! I’ve listened to songs I haven’t hear...         1  
10    I sent it to my 85 year old Dad, and he talks ...         1  
11    I love it! Learning knew things with it eveyda...         1  
12    I purchased this for my mother who is having k...         1  
13             

In [6]:
def text_cleaner(data):
    #Removes non-letter characters 
    letters_only = re.sub("[^a-zA-Z]"," ",data)
    lower_case = letters_only.lower()
    words = lower_case.split()
    #Takes out unmeaningful stop words
    filtered = []
    for w in words:
        if w not in stopwords.words('english'):
            filtered.append(w)
    #Creates a long string with words 
    clean_text = " ".join(words)
    return clean_text

In [7]:
#Cleans the reviews column
data["verified_reviews"] = data["verified_reviews"].apply(text_cleaner)

In [8]:
#Split into training & testing set

(train_reviews, test_reviews, train_target, test_target) = \
train_test_split(data['verified_reviews'], data['rating'],\
test_size = 0.2)

In [9]:
#Bag of Words with 5000 most common words

vectorizer = CountVectorizer(analyzer='word', \
max_features = 5000)

#Find the 5000 most common words in the train set
vectorizer.fit(train_reviews)

#Look at which words are most common
print(vectorizer.get_feature_names())

['abay', 'abd', 'abilities', 'ability', 'able', 'abode', 'about', 'above', 'absolutely', 'ac', 'accent', 'acceptable', 'accepting', 'access', 'accessable', 'accessible', 'accessing', 'accessories', 'accidentally', 'accompanying', 'accomplish', 'accomplished', 'according', 'accordingly', 'account', 'accounts', 'accuracy', 'accurately', 'accustom', 'acknowledge', 'acoustical', 'across', 'act', 'acting', 'action', 'actions', 'activate', 'activated', 'activating', 'activation', 'actively', 'activities', 'actually', 'ad', 'adapted', 'adapter', 'adapting', 'add', 'added', 'addict', 'addicted', 'addicts', 'adding', 'addition', 'additional', 'additionally', 'addons', 'addressed', 'addresses', 'adds', 'adept', 'adequate', 'adjacent', 'adjust', 'adjusting', 'adjustment', 'adjusts', 'admit', 'adopters', 'ads', 'adults', 'advanced', 'advantage', 'advertise', 'advertised', 'advertisement', 'advertising', 'advice', 'advise', 'advised', 'aesthetic', 'af', 'affirm', 'afford', 'affordable', 'afraid', '

In [10]:
#Tranform the data

train_word_columns = vectorizer.transform(train_reviews).toarray()
test_word_columns = vectorizer.transform(test_reviews).toarray()

#Take a look at what one of these data sets looks like now
print(train_word_columns)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
#Feed into Multinomial Naive Bayes

mnb = MultinomialNB()
mnb.fit(train_word_columns,train_target)
preds = mnb.predict(test_word_columns)
print(accuracy_score(preds,test_target))

0.753968253968254


In [26]:
#Alpha is a smoothing parameter for Multinomial Naive Bayes

mnb = MultinomialNB(alpha = 0.3)
mnb.fit(train_word_columns,train_target)
preds = mnb.predict(test_word_columns)
print(accuracy_score(preds,test_target))

0.7777777777777778


In [13]:
#Feed into Gaussian Naive Bayes

gnb = GaussianNB()
gnb.fit(train_word_columns,train_target)
preds = gnb.predict(test_word_columns)
print(accuracy_score(preds,test_target))

0.4031746031746032


In [27]:
#Feed into Bernoulli Naive Bayes

bnb = BernoulliNB()
bnb.fit(train_word_columns,train_target)
preds = bnb.predict(test_word_columns)
print(accuracy_score(preds,test_target))

0.7158730158730159


In [28]:
#Feed into Support Vector Machine

svc = SVC()
svc.fit(train_word_columns,train_target)
preds = svc.predict(test_word_columns)
print(accuracy_score(preds,test_target))

0.7158730158730159


In [16]:
#Support Vector Machines with PCA

pca = PCA(n_components=400, whiten = 'True')
pca.fit(train_word_columns)
train_transformed = pca.transform(train_word_columns)
test_transformed = pca.transform(test_word_columns)

svc = SVC()
svc.fit(train_transformed, train_target)
preds = svc.predict(test_transformed)
print(accuracy_score(preds,test_target))

0.7571428571428571


In [17]:
#Gaussian Naive Bayes with PCA

gnb = GaussianNB()
gnb.fit(train_transformed, train_target)
preds = gnb.predict(test_transformed)
print(accuracy_score(preds,test_target))

0.6095238095238096


In [18]:
#Bernoulli Naive Bayes with PCA

bnb = BernoulliNB()
bnb.fit(train_transformed, train_target)
preds = bnb.predict(test_transformed)
print(accuracy_score(preds,test_target))

0.665079365079365


In [19]:
#Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()
rfc.fit(train_word_columns,train_target)
preds = rfc.predict(test_word_columns)
print(accuracy_score(preds,test_target))

C:\Users\rebec\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


0.8031746031746032


In [20]:
#Find optimal number of decision trees in the random forest

rfc = RandomForestClassifier(n_estimators = 100)
rfc.fit(train_word_columns,train_target)
preds = rfc.predict(test_word_columns)
print(accuracy_score(preds,test_target))

0.8095238095238095


In [21]:
#Find optimal number of decision trees in the random forest

rfc = RandomForestClassifier(n_estimators = 50)
rfc.fit(train_word_columns,train_target)
preds = rfc.predict(test_word_columns)
print(accuracy_score(preds,test_target))

0.8063492063492064
